config/routes.rb
Rails.application.routes.draw do
  # Overrides urls for devise paths
  # Taken from http://stackoverflow.com/a/3845245 | doritostains | 11th May 2015, 10:12 am
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :courses do
    patch 'remove_member/:user_id' => 'courses#remove_member', as: :remove_member, on: :member
    get 'statistics', on: :member
    get 'json' => 'courses#json', as: :json, on: :member

    resources :questions, except: :index do
      patch 'solve' => 'questions#mark_as_solved!', as: :mark_as_solved, on: :member

      resources :comments, except: [:index, :new, :show] do
        patch 'helpful' => 'comments#mark_as_helpful!', as: :mark_as_helpful, on: :member
      end
    end
  end

  resources :file_attachments, only: :destroy

  match '*path', to: 'application#raise_routing_error', via: :all

  root 'courses#index'
end

app/views/partials/_add_comment.haml
#add-comment.add-comment
  %h2
    Write an answer

  .description
    Enter a helpful answer or solution to help

  = form_for [@question.course, @question, @new_comment] do |f|
    .page
      .field
        = render 'partials/code_field', form_content: { form: f, content: :content, object: @new_comment }

      .divider

      .actions
        .fa-input.button.submit
          = f.button type: 'submit', class: 'green' do
            %i.fa.fa-check-circle
            Answer

      .clear

app/views/partials/_board_form.haml
#board-form.board-form
  .menu
    %ul
      %li{ class: 'active' }
        %a{ href: '#information' }
          Information

      %li
        %a{ href: '#content' }
          Content

      %li
        %a{ href: '#attachments' }
          Attachments

      %li
        %a{ href: '#members' }
          Members

      .clear

  = form_for @board do |f|
    #information.page.active
      .field
        .fa-input.board-title
          %i.fa.fa-calendar-o
          = f.text_field :title, autofocus: true, placeholder: 'Title'

        = handle_form_error(:title, @board)

      .field
        .fa-input.board-description
          %i.fa.fa-pencil
          = f.text_field :description, placeholder: 'Description'

        = handle_form_error(:description, @board)

      .divider

      .field.privacy
        .table
          .title
            Privacy

          .options
            = f.radio_button :public, true
            = f.label :public, 'Public', value: 'true'

            = f.radio_button :public, false, checked: true
            = f.label :public, 'Private', value: 'false'

          .clear

      .divider

      .field.submission
        .table
          .title
            Submission until

          .options
            .fa-input.datetime
              %i.fa.fa-calendar
              = f.text_field :submission_until, placeholder: 'Select date'

            = handle_form_error(:submission_until, @board)

          .clear

      .divider

    #content.page
      content

    #attachments.page
      attachments

    #members.page
      members

    .actions
      .fa-input.button.submit
        = f.button type: 'submit', class: 'green' do
          %i.fa.fa-check-circle
          Create board

      .clear

:javascript
  $(document).on('ready page:load', function() {
    var boardForm = new BoardForm('.board-form');
  });

app/views/partials/_code_field.haml
.code-field
  .options
    %ul
      %li{ class: 'active' }
        %a{ href: '#source' }
          Source

      %li
        %a{ href: '#preview' }
          Preview

      .clear

  .clear

  .code
    #source.source.page.active
      = form_content[:form].text_area form_content[:content], placeholder: 'Write something (you can use Markdown)', class: 'code'
      = handle_form_error(form_content[:content], form_content[:object])

    #preview.page.preview.markdown-body

app/views/partials/_comment_thread.haml
- if @question.comments(true).present?
  #comment-thread.comment-thread
    %h2
      Comments

    - @question.comments(true).no_reply.order('created_at asc').each do |comment|
      .comment
        .left-comment-col
          .comment-content
            .markdown-body
              = comment.markdown.html_safe

        .right-comment-col
          - if comment.question.author === current_user && comment.author != current_user
            .actions
              %a{ href: mark_as_helpful_course_question_comment_path(@question.course, @question, comment), title: 'Mark as helpful', class: "verify #{active?(comment.verified)}", data: { method: 'patch' } }
                %i.fa.fa-check

          - elsif comment.verified
            .actions
              %a{ title: 'The question author marked this answer as helpful', class: 'verify active' }
                %i.fa.fa-check

        .clear

        .comment-actions
          .action.reply
            %a{ href: '#reply', title: 'Reply', class: 'reply' }
              %i.fa.fa-reply

          - if comment.has_author?(current_user)
            .action.edit
              %a{ href: edit_course_question_comment_path(@question.course, @question, comment), title: 'Edit comment' }
                %i.fa.fa-pencil

            .action.delete
              %a{ href: course_question_comment_path(@question.course, @question, comment), title: 'Delete comment', class: 'red', data: { method: 'delete', confirm: 'Are you sure?' } }
                %i.fa.fa-trash

          .clear

          = form_for [@question.course, @question, comment.replies.new] do |f|
            .add-reply.page
              %h2
                Reply

              .description
                Write a reply

              .field
                = render 'partials/code_field', form_content: { form: f, content: :content, object: comment.replies.new }
                = f.hidden_field :comment_id, value: comment.id

              .divider

              .actions
                .fa-input.button.submit
                  = f.button type: 'submit', class: 'green' do
                    %i.fa.fa-check-circle
                    Reply

              .clear


        .comment-footer
          .description
            = "Answered on #{comment.created_at.to_formatted_s(:long)}"

          .creator
            .info
              .description
                Answered by

              .username
                = comment.author.username

            .avatar
              = image_tag(comment.author.avatar_image(:thumbnail))

          .clear

        - if comment.replies(true).present?
          .replies
            - comment.replies.order('created_at asc').each do |reply|
              .comment-reply
                .avatar.tiny
                  = image_tag(reply.author.avatar_image(:tiny))

                .description
                  = "#{reply.author.username.humanize} replied on #{reply.created_at.to_formatted_s(:long)}"

                - if reply.question.author === current_user && reply.author != current_user
                  .actions
                    %a{ href: mark_as_helpful_course_question_comment_path(@question.course, @question, reply), title: 'Mark as helpful', class: "verify #{active?(reply.verified)}", data: { method: 'patch' } }
                      %i.fa.fa-check

                - elsif reply.verified
                  .actions
                    %a{ title: 'The question author marked this answer as helpful', class: 'verify active' }
                      %i.fa.fa-check

                .clear

                .comment-content
                  .markdown-body
                    = reply.markdown.html_safe

                - if reply.has_author?(current_user)
                  .comment-actions
                    .action.edit
                      %a{ href: edit_course_question_comment_path(@question.course, @question, reply), title: 'Edit reply' }
                        %i.fa.fa-pencil

                    .action.delete
                      %a{ href: course_question_comment_path(@question.course, @question, reply), title: 'Delete reply', class: 'red', data: { method: 'delete', confirm: 'Are you sure?' } }
                        %i.fa.fa-trash

                    .clear

                .divider

        .divider

app/views/partials/_course_form.haml
#course-form.course-form
  .menu
    %ul
      %li{ class: 'active' }
        %a{ href: '#information' }
          Information

      %li
        %a{ href: '#lectures', id: 'course-lectures' }
          Lectures

      %li
        %a{ href: '#achievements' }
          Achievements

      %li
        %a{ href: '#members' }
          Members

      .clear

  = form_for @course do |f|
    #information.page.active
      .field
        .fa-input.course-title
          %i.fa.fa-calendar-o
          = f.text_field :title, autofocus: true, placeholder: 'Title'

        = handle_form_error(:title, @course)

      .field
        .fa-input.course-description
          %i.fa.fa-pencil
          = f.text_field :description, placeholder: 'Description'

        = handle_form_error(:description, @course)

      .divider

      .field.privacy
        .table
          .title
            Privacy

          .options
            = f.radio_button :public, true
            = f.label :public, 'Public', value: 'true'

            = f.radio_button :public, false
            = f.label :public, 'Private', value: 'false'

          .clear

      .divider

    #lectures.page
      .lectures.list
        = f.fields_for :lectures, @course.lectures do |l|
          %br
          %br
          = l.label :title, value: "Lecture ##{l.options[:child_index] + 1}"
          = l.text_field :title, placeholder: 'Title (e. g. Lecture 1: Ruby basics)'

      %a{ href: '#', id: 'add-lecture-link', class: 'add-lecture blue' }
        Add lecture

    #achievements.page
      .achievements.list
        = f.fields_for :achievements, @course.achievements do |a|
          .entry
            .row
              = a.label :title, value: "Achievement ##{a.options[:child_index] + 1}"
              = a.text_field :title, placeholder: 'Title (e. g. +5% Course grading)'

            .row
              = a.text_area :description, placeholder: 'Description'

            .row
              = a.label :points
              = a.text_field :points, placeholder: '1'


      %a{ href: '#', class: 'add-achievement blue' }
        Add achievement

    #members.page

      - if @course.members.present?
        .user-list
          - @course.members.each do |member|
            .user
              .name
                = member.username

              .delete
                = link_to content_tag(:i, nil, class: 'fa fa-trash-o'), remove_member_course_path(@course, member), class: 'red', method: :patch, data: { confirm: 'Are you sure?' }

              .clear

          .clear

        .divider

      .field
        .user-selector
          .add
            = f.text_area :user_emails, placeholder: 'Enter comma separated user e-mail addresses'

      .divider

    .actions
      .fa-input.button.submit
        = f.button type: 'submit', class: 'green' do
          %i.fa.fa-check-circle
          Finish

      .clear

:javascript
  $(document).on('ready page:load', function() {
    var courseForm = new CourseForm('.course-form');
  });

app/views/partials/_dashboard.haml
#dashboard.dashboard
  %h1
    Dashboard

  .box
    - if @owned_courses.present?
      %h2
        Courses you created

      .description
        These courses have been created by you.

      %ul
        - @owned_courses.each do |course|
          %li
            %a{ href: course_path(course) }
              .id
                = course.formatted_id

              .info
                .title
                  = course.title

                .clear
                .description
                  = course.description

              .actions
                %a{ href: statistics_course_path(course), title: 'Show statistics' }
                  %i.fa.fa-trophy

                %a{ href: edit_course_path(course) }
                  %i.fa.fa-pencil

                %a{ href: course_path(course), class: 'red', data: { method: 'delete', confirm: 'Are you sure?' } }
                  %i.fa.fa-trash

              .clear

      - if @owned_courses.present? && @assigned_courses.present?
        .divider

    - if @assigned_courses.present?
      %h2
        Courses you are assigned to

      .description
        You are contributing to these courses.

      %ul
        - @assigned_courses.each do |course|
          %li
            %a{ href: course_path(course) }
              .id
                = course.formatted_id

              .info
                .title
                  = course.title

                .clear
                .description
                  = course.description

              .creator
                .description
                  Created by

                .clear

                .username
                  = course.owner.username

                .avatar
                  = image_tag(course.owner.avatar_image(:tiny))

              .clear

app/views/partials/_footer.haml
%footer.footer
  &copy; 2015 grasp

app/views/partials/_header.haml
- if user_signed_in?
  %header.header
    .content
      .left
        %a{ href: root_path }
          = image_tag('logo-small.png')

      .center
        &nbsp;

      .right
        .user
          .avatar
            = image_tag(current_user.avatar_image(:tiny))

          .username
            = current_user.username

        .nav-bar
          .nav-item
            %a{ href: new_course_path, title: 'Create a new course' }
              %i.fa.fa-plus

          .nav-item
            %a{ href: edit_user_registration_path, title: 'Edit profile' }
              %i.fa.fa-gear

          .nav-item
            %a{ href: destroy_user_session_path, title: 'Logout', data: { method: 'delete' } }
              %i.fa.fa-sign-out

          .clear

      .clear

app/views/partials/_logo.haml
#logo.logo
  = image_tag('logo-big.png')

app/views/partials/_messages.haml
- if notice
  .message.success
    .icon
      %i.fa.fa-check-circle

    .text
      = notice

- if alert
  .message.error
    .icon
      %i.fa.fa-times-circle

    .text
      = alert

:javascript
  $(document).on('ready page:load', function() {
    var message = new Message('.message');
  });

app/views/partials/_navigation.haml
#navigation.navigation
  .link
    = link_to 'Home', root_path

  .link
    = link_to 'Courses', courses_path

  - if @course.present?
    .link
      = link_to "Course: #{@course.title}", @course

  - elsif @question.course.present?
    .link
      = link_to "Course: #{@question.course.title}", course_path(@question.course)

  .clear

app/views/partials/_question_form.haml
#question-form.question-form
  = form_for [@question.course, @question], html: { multipart: true } do |f|
    .page
      .field
        = render 'partials/code_field', form_content: { form: f, content: :content, object: @question }

      .divider

      .field.category
        .table
          .title
            Category

          .options
            = f.select(:category, Question::CATEGORIES.map { |category| [category.humanize, category] })

          .clear

      .divider

      .field.category
        .table
          .title
            Lecture

          .options
            = f.select(:lecture_id, @question.course.lectures.map { |lecture| [lecture.title.humanize, lecture.id] })

          .clear

      .divider

      .field.privacy
        .table
          .title
            Username visibility

          .options
            = f.radio_button :anonymous, true
            = f.label :anonymous, 'Anonymous', value: 'true'

            = f.radio_button :anonymous, false
            = f.label :anonymous, 'Public', value: 'false'

          .clear

      .divider

      .field.file-upload
        .table
          .title
            File attachments

          .options
            = file_field_tag 'files[]', type: :file, multiple: true
            = handle_form_error(:file_attachments, @question)

          .clear

      .divider

      - if @question.file_attachments.present?
        .field.file-attachments
          .table
            .title
              Attached files

            .options
              - @question.file_attachments.each do |file|
                .attachment
                  .preview
                    = image_tag(file.preview_image)

                  .name
                    = file.file_file_name

                  .delete
                    = link_to content_tag(:i, nil, class: 'fa fa-trash-o'), file, class: 'red', method: :delete, data: { confirm: 'Are you sure?' }

            .clear

        .divider

    .actions
      .fa-input.button.submit
        = f.button type: 'submit', class: 'green' do
          %i.fa.fa-check-circle
          Finish

      .clear

:javascript
  $(document).on('ready page:load', function() {
    var courseForm = new CourseForm('.course-form');
  });

app/views/partials/_welcome.haml
#welcome.welcome
  %h1
    = "Welcome to grasp, #{current_user.username}!"

  %p
    You haven't created any courses yet.

  .fa-input.button.small
    = button_to new_course_path, class: 'green', id: 'create-course-button', method: :get do
      %i.fa.fa-plus-circle
      Create your first course

app/views/partials/_your_questions.haml
- if @course.questions.by_author(current_user).present?
  #your-questions.your-questions.sidebar-element
    .box
      %h2
        Your questions

      .list
        - @course.questions.by_author(current_user).each do |question|
          %a{ href: course_question_path(@course, question) }
            .question
              .title
                = truncate(question.content, length: 35)

              .category
                = question.category.to_s.humanize

              .clear
              
              .date
                = "Asked on #{question.created_at.to_formatted_s(:long)}"

          .divider